---
test_switches:
  - {hostname: pynet-sw1, ip_addr: 1.1.1.1, default_gateway: 1.1.1.254, secret: 12345, access_vlan: 800, snmp_community: a1b2c3}  
  - {hostname: pynet-sw2, ip_addr: 1.1.2.1, default_gateway: 1.1.2.254, secret: 12345, access_vlan: 800, snmp_community: a1b2c3}
  - {hostname: pynet-sw3, ip_addr: 1.1.3.1, default_gateway: 1.1.3.254, secret: 12345, access_vlan: 800, snmp_community: a1b2c3} 
  - {hostname: pynet-sw4, ip_addr: 1.1.4.1, default_gateway: 1.1.4.254, secret: 12345, access_vlan: 800, snmp_community: a1b2c3}

test_switches2:
  - {hostname: pynet-sw1, ip_addr: 1.1.1.1, default_gateway: 1.1.1.254, secret: 12345, access_vlan: 800, snmpv3: True, snmp_community: a1b2c3}  
  - {hostname: pynet-sw2, ip_addr: 1.1.2.1, default_gateway: 1.1.2.254, secret: 12345, access_vlan: 800, snmpv3: True, snmp_community: a1b2c3}
  - {hostname: pynet-sw3, ip_addr: 1.1.3.1, default_gateway: 1.1.3.254, secret: 12345, access_vlan: 800, snmpv3: False, snmp_community: a1b2c3} 
  - {hostname: pynet-sw4, ip_addr: 1.1.4.1, default_gateway: 1.1.4.254, secret: 12345, access_vlan: 800, snmpv3: False, snmp_community: a1b2c3}
