---

- name: Cisco IOS testing
  hosts: pynet-rtr1
  gather_facts: False

  tasks: 
    - name: Testing file transfer
      cisco_file_transfer: 
          source_file="/home/earslan/pynet_class/class6/cisco_ea.txt"
          dest_file=cisco_ea.txt
          overwrite=true
          enable_scp=true   
          host={{ host }}
          port={{ port }}	
          username={{ username }}
          password={{ password }}
